/// Centralized skills catalogue.
///
/// Use [kAllSkills] for autocomplete / search suggestions.
/// Use [kSkillsByCategory] when you need a grouped picker UI.
library;

// ─── Categorised skills ─────────────────────────────────────────────────────

const Map<String, List<String>> kSkillsByCategory = {
  'Programming Languages': [
    'Python',
    'Java',
    'JavaScript',
    'TypeScript',
    'C',
    'C++',
    'C#',
    'Go',
    'Rust',
    'Swift',
    'Kotlin',
    'Dart',
    'PHP',
    'Ruby',
    'R',
    'Scala',
    'Perl',
    'MATLAB',
    'Shell Scripting',
    'Bash',
    'PowerShell',
    'Lua',
    'Haskell',
    'Elixir',
    'Clojure',
    'F#',
    'Groovy',
    'Objective-C',
    'COBOL',
    'Assembly',
  ],

  'Frontend Development': [
    'HTML',
    'CSS',
    'React',
    'Vue.js',
    'Angular',
    'Next.js',
    'Nuxt.js',
    'Svelte',
    'SASS / SCSS',
    'Tailwind CSS',
    'Bootstrap',
    'Material UI',
    'Chakra UI',
    'jQuery',
    'Redux',
    'Zustand',
    'Webpack',
    'Vite',
    'Gatsby',
    'Storybook',
    'Three.js',
    'WebGL',
  ],

  'Backend Development': [
    'Node.js',
    'Express.js',
    'NestJS',
    'Django',
    'Flask',
    'FastAPI',
    'Spring Boot',
    'Laravel',
    'Ruby on Rails',
    'ASP.NET',
    'Gin (Go)',
    'gRPC',
    'REST API Design',
    'GraphQL',
    'Microservices',
    'WebSockets',
    'OAuth',
    'JWT',
    'Message Queues',
    'RabbitMQ',
    'Apache Kafka',
  ],

  'Mobile Development': [
    'Flutter',
    'React Native',
    'Android Development',
    'iOS Development',
    'Xamarin',
    'Ionic',
    'Capacitor',
    'SwiftUI',
    'Jetpack Compose',
  ],

  'DevOps & Cloud': [
    'AWS',
    'Google Cloud Platform',
    'Microsoft Azure',
    'Docker',
    'Kubernetes',
    'Terraform',
    'Ansible',
    'Jenkins',
    'GitHub Actions',
    'GitLab CI/CD',
    'Linux',
    'Nginx',
    'Apache',
    'Prometheus',
    'Grafana',
    'ELK Stack',
    'CI/CD',
    'Serverless',
    'Firebase',
    'Supabase',
    'Cloudflare',
    'Heroku',
    'Vercel',
    'Netlify',
  ],

  'Databases': [
    'MySQL',
    'PostgreSQL',
    'MongoDB',
    'Redis',
    'SQLite',
    'Firebase Firestore',
    'Cassandra',
    'Oracle DB',
    'DynamoDB',
    'Neo4j',
    'Elasticsearch',
    'InfluxDB',
    'Microsoft SQL Server',
    'MariaDB',
    'Prisma ORM',
    'Sequelize',
    'SQLAlchemy',
  ],

  'Testing & QA': [
    'Manual Testing',
    'Selenium',
    'Appium',
    'Jest',
    'Cypress',
    'Playwright',
    'JUnit',
    'TestNG',
    'PyTest',
    'Postman',
    'API Testing',
    'Load Testing',
    'JMeter',
    'Unit Testing',
    'Integration Testing',
    'End-to-End Testing',
    'Test-Driven Development (TDD)',
    'Behaviour-Driven Development (BDD)',
    'Cucumber',
    'Robot Framework',
    'Performance Testing',
    'Security Testing',
    'Accessibility Testing',
    'Regression Testing',
    'Smoke Testing',
    'Test Case Design',
    'Bug Tracking',
    'Quality Assurance',
  ],

  'Data Science & AI': [
    'Machine Learning',
    'Deep Learning',
    'TensorFlow',
    'PyTorch',
    'Keras',
    'scikit-learn',
    'Pandas',
    'NumPy',
    'Matplotlib',
    'Seaborn',
    'Natural Language Processing (NLP)',
    'Computer Vision',
    'Data Analysis',
    'Data Visualization',
    'Power BI',
    'Tableau',
    'Apache Spark',
    'Hadoop',
    'Statistics',
    'A/B Testing',
    'Feature Engineering',
    'Model Deployment',
    'MLOps',
    'LLMs',
    'Prompt Engineering',
    'Data Engineering',
    'ETL Pipelines',
    'Data Warehousing',
    'Snowflake',
  ],

  'UI/UX Design': [
    'Figma',
    'Adobe XD',
    'Sketch',
    'InVision',
    'Zeplin',
    'Wireframing',
    'Prototyping',
    'User Research',
    'Usability Testing',
    'Information Architecture',
    'Interaction Design',
    'Design Systems',
    'Accessibility (WCAG)',
    'User Flows',
    'Journey Mapping',
    'Heuristic Evaluation',
    'Card Sorting',
    'A/B Testing (UX)',
    'Micro-interactions',
    'Responsive Design',
  ],

  'Graphic Design': [
    'Adobe Photoshop',
    'Adobe Illustrator',
    'Adobe InDesign',
    'Canva',
    'CorelDRAW',
    'Motion Graphics',
    'Adobe After Effects',
    'Adobe Premiere Pro',
    'Branding',
    'Typography',
    'Color Theory',
    'Logo Design',
    'Print Design',
    'Packaging Design',
    'Illustration',
    'Icon Design',
    'Infographic Design',
    '3D Design',
    'Blender',
    'Cinema 4D',
  ],

  'Cybersecurity': [
    'Penetration Testing',
    'Ethical Hacking',
    'Network Security',
    'Application Security',
    'OWASP',
    'Cryptography',
    'Incident Response',
    'SIEM',
    'Vulnerability Assessment',
    'Burp Suite',
    'Metasploit',
    'Wireshark',
    'OSINT',
    'Digital Forensics',
    'Zero Trust Security',
    'SOC Analysis',
    'Malware Analysis',
    'Reverse Engineering',
    'Cloud Security',
    'Identity & Access Management',
    'Risk Management',
    'Compliance (ISO 27001)',
  ],

  'Blockchain & Web3': [
    'Solidity',
    'Ethereum',
    'Smart Contracts',
    'DeFi',
    'NFTs',
    'Web3.js',
    'Ethers.js',
    'Hardhat',
    'Truffle',
    'Polkadot',
    'Solana',
    'Hyperledger',
    'IPFS',
    'DApp Development',
    'Tokenomics',
    'Crypto Wallets',
  ],

  'Product Management': [
    'Product Strategy',
    'Roadmap Planning',
    'Agile',
    'Scrum',
    'Kanban',
    'JIRA',
    'Confluence',
    'User Stories',
    'Market Research',
    'Competitive Analysis',
    'OKRs',
    'KPI Tracking',
    'Stakeholder Management',
    'Product Analytics',
    'Feature Prioritisation',
    'Go-to-Market Strategy',
    'Product Discovery',
    'Sprint Planning',
  ],

  'Marketing & Growth': [
    'SEO',
    'SEM',
    'Content Marketing',
    'Social Media Marketing',
    'Email Marketing',
    'Google Ads',
    'Meta Ads',
    'Growth Hacking',
    'Brand Strategy',
    'Copywriting',
    'Influencer Marketing',
    'CRM',
    'HubSpot',
    'Google Analytics',
    'Conversion Rate Optimisation',
    'Affiliate Marketing',
    'Video Marketing',
    'Podcast Marketing',
    'Community Management',
    'PR & Communications',
  ],

  'Finance & Fintech': [
    'Financial Modeling',
    'Microsoft Excel',
    'Investment Analysis',
    'Accounting',
    'Risk Management',
    'Derivatives',
    'Equity Research',
    'Portfolio Management',
    'Valuation',
    'Bloomberg Terminal',
    'QuickBooks',
    'Financial Reporting',
    'Tally',
    'GST Filing',
    'Tax Planning',
    'Corporate Finance',
    'Venture Capital',
    'Private Equity',
    'Fintech Development',
    'Payment Gateways',
  ],

  'Law & Legal': [
    'Contract Drafting',
    'Legal Research',
    'Intellectual Property (IP)',
    'Corporate Law',
    'Employment Law',
    'GDPR Compliance',
    'Privacy Law',
    'Legal Writing',
    'Litigation',
    'Arbitration',
    'Regulatory Compliance',
    'Due Diligence',
    'Mergers & Acquisitions',
    'Tax Law',
    'Criminal Law',
    'Civil Law',
    'Family Law',
    'Real Estate Law',
    'Patent Law',
    'Trademark Law',
    'International Law',
    'Competition Law',
    'Insolvency & Bankruptcy',
    'Constitutional Law',
    'Environmental Law',
    'Cyber Law',
    'Legal Tech',
    'Contract Management',
    'Legal Ops',
  ],

  'Other': [
    'Research',
    'Technical Writing',
    'Academic Writing',
    'Public Speaking',
    'Teaching & Mentoring',
    'Project Management',
    'Business Analysis',
    'Operations Management',
    'Supply Chain',
    'HR & Recruitment',
    'Event Management',
    'Video Editing',
    'Content Creation',
    'Photography',
    'Game Development',
    'Unity',
    'Unreal Engine',
    'AR / VR Development',
    'IoT Development',
    'Embedded Systems',
    'PCB Design',
    'Robotics',
    'CAD Design',
    'AutoCAD',
    'SolidWorks',
    'Competitive Programming',
    'Open Source Contribution',
  ],
};

// ─── Flat sorted list — use this for autocomplete suggestions ───────────────

final List<String> kAllSkills = () {
  final all = <String>{};
  for (final skills in kSkillsByCategory.values) {
    all.addAll(skills);
  }
  final sorted = all.toList()..sort((a, b) => a.toLowerCase().compareTo(b.toLowerCase()));
  return sorted;
}();

/// Returns up to [limit] suggestions from [kAllSkills] that contain [query].
/// Case-insensitive. Returns an empty list for blank queries.
List<String> suggestSkills(String query, {int limit = 8}) {
  final q = query.trim().toLowerCase();
  if (q.isEmpty) return const [];
  return kAllSkills
      .where((s) => s.toLowerCase().contains(q))
      .take(limit)
      .toList();
}
