// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2hCvyfSl46WIU5lrQgsOOs99ARduYACI',
    appId: '1:990483552835:android:9e25738abe6a8f9eb252f6',
    messagingSenderId: '990483552835',
    projectId: 'proco-3d9fe',
    storageBucket: 'proco-3d9fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzx7hotO5MB5as9BYzR0Tb7PgxyY-8DWs',
    appId: '1:990483552835:ios:6dd5f2067e1ae8cab252f6',
    messagingSenderId: '990483552835',
    projectId: 'proco-3d9fe',
    storageBucket: 'proco-3d9fe.firebasestorage.app',
    iosBundleId: 'com.example.jobhubV1',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEOFxxIm27ouo1USfKG6vCX4QpesXwLFc',
    appId: '1:990483552835:web:b936294f36d8654cb252f6',
    messagingSenderId: '990483552835',
    projectId: 'proco-3d9fe',
    authDomain: 'proco-3d9fe.firebaseapp.com',
    storageBucket: 'proco-3d9fe.firebasestorage.app',
    measurementId: 'G-8DNTQ6XHPN',
  );

}